version: '2.1'

networks:
  hyperiot:
    name: hyperiot
    driver: bridge

services:
  zookeeper:
    extends:
     file: docker-compose-svil-basic.yml
     service: zookeeper

  namenode:
    extends:
     file: docker-compose-svil-basic.yml
     service: namenode

  resourcemanager:
    extends:
     file: docker-compose-svil-basic.yml
     service: resourcemanager
    depends_on:
      - "namenode"
    links:
      - "namenode"

  historyserver:
    extends:
     file: docker-compose-svil-basic.yml
     service: historyserver
    depends_on:
      - "namenode"
    links:
      - "namenode"

  nodemanager:
    extends:
     file: docker-compose-svil-basic.yml
     service: nodemanager
    depends_on:
      - "namenode"
      - "resourcemanager"
    links:
      - "namenode"
      - "resourcemanager"

  datanode1:
    extends:
     file: docker-compose-svil-basic.yml
     service: datanode1
    depends_on:
      - "namenode"
    links:
      - "namenode"

  datanode2:
    extends:
     file: docker-compose-svil-basic.yml
     service: datanode2
    depends_on:
      - "namenode"
    links:
      - "namenode"

  datanode3:
    extends:
     file: docker-compose-svil-basic.yml
     service: datanode3
    depends_on:
      - "namenode"
    links:
      - "namenode"

  hbase-master:
    extends:
     file: docker-compose-svil-basic.yml
     service: hbase-master

  hbase-region:
    extends:
     file: docker-compose-svil-basic.yml
     service: hbase-region
    depends_on:
      - hbase-master

  postgresql:
    extends:
     file: docker-compose-svil-basic.yml
     service: postgresql
