package it.acsoftware.hyperiot.stormmanager.model;

public enum MessageConversionStrategy {
     HDFS_DLQ_HOUR_MESSAGE_STRATEGY,
     HDFS_DLQ_DAY_MESSAGE_STRATEGY,
     HDFS_DLQ_MONTH_MESSAGE_STRATEGY,
     HDFS_DLQ_YEAR_MESSAGE_STRATEGY,
     HDFS_DLQ_SEMESTER_MESSAGE_STRATEGY,
     HDFS_DLQ_QUARTER_MESSAGE_STRATEGY,
     HBASE_DLQ_EVENT_TABLE_MESSAGE_STRATEGY ,
     HBASE_DLQ_AVRO_TABLE_MESSAGE_STRATEGY ,
     HBASE_DLQ_TIMELINE_TABLE_MESSAGE_STRATEGY,
     HBASE_DLQ_ALARM_TABLE_MESSAGE_STRATEGY,
     HBASE_DLQ_EVENT_RULE_STATE_MESSAGE_STRATEGY,
     HBASE_DLQ_ERROR_TABLE_MESSAGE_STRATEGY
}
